### ISSUE TITLE
Add user

### ISSUE THREAD

**Issue by haucongle** [bestmomo/laravel5-example#29]
Hi, I logined with Adminstrator role. I acces Administration Panel and add new user.
I get a error about miss argurment.
Can you help me to fix it?
Thanks!

**Comment by haucongle** [comment]
who can help me? Please!

**Comment by odin4** [comment]
Got the similar error while trying to add a new user.

- Missing argument 2 for App\Repositories\UserRepository::store(), called in C:\xampp\htdocs\sample\app\Http\Controllers\UserController.php on line 111 and defined

Total noob to laravel here. Please help.

**Comment by odin4** [comment]
I was able to create a new user by removing
$confirmation_code from 
store($inputs, $confirmation_code) function in the UserRepository.php and removing $inputs['confirmation_code'] = $confirmation_code;
from within the function.
I dont know what the confirmation code is for yet at this for but it does not seem to be needed because only admins can add users.

- total noob here.

**Comment by bestmomo** [comment]
Hi,

I think it's corrected with [this commit](https://github.com/bestmomo/laravel5-example/commit/da9922f9d291a8acde5a6374f36e0759edb39aaa). As I cant test it for now tell me if  it's ok.

**Comment by odin4** [comment]
Thanks.

**Comment by bestmomo** [comment]
I made the corrction on [this commit](https://github.com/bestmomo/laravel5-example/commit/20ebfcdfb45f83022c6171f229bd942655bfcaa3) but I should also add "confirmed" in user administration.
