### ISSUE TITLE
proposal: multiple roles for users (privileges)

### ISSUE THREAD

**Issue by UnrulyNatives** [bestmomo/laravel5-example#3]
Your starter site is absolutely great. Would you consider to implement multiple roles for users - just as in a Laravel starter site from here: https://github.com/andrewelkins/Laravel-4-Bootstrap-Starter-Site

If the roles are handled like privileges, it gives much more flexibility.

Thx

**Comment by bestmomo** [comment]
Hello,

Thanks for your proposal.

The related project that you mention uses a 3rd package (Entrust and Confide) to manage roles. I didn't want to use packages for my example because they dont work yet for L5 ! And I want to keep this example as simple as possible, just using Laravel possibilities.

It is not really a starter site, just an example for tutorial. If I had to make a starter site I think I would use some packages to avoid reinvent the wheel.

But i'll think about a simple way to manage many roles for users and if I get a nice and easy one I'll do it.

**Comment by UnrulyNatives** [comment]
Hi.
I managed to include this package into my project: 
https://github.com/romanbican/roles
and it works great.

**Comment by bestmomo** [comment]
This package seems clean and easy.

**Comment by UnrulyNatives** [comment]
Maybe you could contribute to his work as I proposed in this issue:

https://github.com/romanbican/roles/issues/14

the task is totally beyond me.

**Comment by bestmomo** [comment]
I just wonder about ACL package relevance. For my example it's too much because 3 simple roles are easy to manage. For bigger application the question is open.

**Comment by omar-faruk-sust** [comment]
This is nice tutorial. thanks for sharing. i have some question. i am new in Laravel framework and also in version 5. what is the URL of admin panel and registration of this project. i have tried with this url after watching your routing (http://localhost:8000/admin). but it's redirect me to the home page. i will be happy if u give me the admin panel URL and registration URL. thanks a lot

**Comment by bestmomo** [comment]
You must login as admin with **admin@la.fr** email and **admin** as password. So you'll have a link for admin panel in navbar. For registration there is a link in login page.

**Comment by omar-faruk-sust** [comment]
Thanks a lot. i got it. i am trying to learn laravel 5. this project will help me a lot. Happy sharing. :+1:

**Comment by semmy** [comment]
Thax for you sharing this source code. I have a problem, canot login in to admin panel. 
Warrning : TokenMismatchException in VerifyCsrfToken.php line 53.

**Comment by bestmomo** [comment]
Hello, is it a problem on auth login ? Because panel admin access doesn't need token.
